# Generated by Django 3.2 on 2021-07-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
    ]
